[16.0][ADD] pos_daily_sales_reports_category_only
trisdoan/pos pull request #5
Opened 2024-04-02 08:37 UTC by trisdoan

2024-04-03 01:59 UTC, trisdoan commented
DRAFT: working on safe inheritance of views/point_of_sale_view.xml

2024-04-03 12:11 UTC, nilshamerlinck commented
I added a quick fix to `http://fakebox-foodcoop.trobz.com` so you can use it now (a bit late I know!):

Enable IOT box in the POS configuration:

![Screenshot-20240403185351-454x700](https://github.com/trisdoan/pos/assets/511258/3c0b6430-bd38-4256-be37-44ae17fce063)

Then select the Receipt Printer, and update manually in a shell:
```
>>> env["iot.box"].browse(1).ip = "fakebox-foodcoop.trobz.com"
>>> env.cr.commit()
```

![Screenshot-20240403185555-467x434](https://github.com/trisdoan/pos/assets/511258/a10ee618-1ba8-4b3e-bc96-8ac36a8b3cea)

Then every time you print something, it will end up in http://fakebox-foodcoop.trobz.com/receipt

![image](https://github.com/trisdoan/pos/assets/511258/2acb7011-a176-4a49-aa74-86420f8d817d)

2024-04-03 12:11 UTC, nilshamerlinck requested changes

2024-04-03 12:11 UTC, nilshamerlinck commented on pos_daily_sales_reports_category_only/static/src/xml/SaleDetailsReport.xml
> +                                x
```suggestion
                                |
```

2024-04-03 12:11 UTC, nilshamerlinck commented on pos_daily_sales_reports_category_only/static/src/xml/SaleDetailsReport.xml
> +                                x
the x could me misunderstood as a multiplication
while here it's `qty | total`

2024-04-03 12:11 UTC, nilshamerlinck commented on pos_daily_sales_reports_category_only/readme/DESCRIPTION.rst
> +The feature can be disabled by unchecking below box:
```suggestion
This feature is enabled by default on installation of the module. It can be disabled by unticking this setting:
```

2024-04-04 04:31 UTC, nilshamerlinck approved these changes

2024-04-04 09:04 UTC, closed without merging